api/urls.py
from django.conf.urls import url

from . import views

app_name = 'api'

# Create a router and register our viewsets with it.
# router = DefaultRouter()
# router.register(r'items', views.ItemViewSet)
# router.register(r'users', views.UserViewSet)
# router.register(r'shops', views.ShopViewSet)

urlpatterns = [
    url(r'^$', views.api_root, name='root'),
    # url(r'^', include(router.urls)),

    url(r'^items/$', views.ItemList.as_view(), name='item-list'),
    url(r'^items/(?P<pk>[0-9]+)/$', views.ItemDetail.as_view(), name='item-detail'),

    url(r'^users/$', views.UserList.as_view(), name='user-list'),
    url(r'^users/(?P<pk>[0-9]+)/$', views.UserDetail.as_view(), name='user-detail'),

    url(r'^profile/$', views.UserProfileDetail.as_view(), name='profile'),

    url(r'^shops/$', views.ShopList.as_view(), name='shop-list'),
    url(r'^shops/(?P<pk>[0-9]+)/$', views.ShopDetail.as_view(), name='shop-detail'),

    # url(r'^reviews/(?P<pk>[0-9]+)/$', views.ReviewDetail.as_view(), name='review-detail'),
    url(r'^reviews/$', views.ReviewCreateView.as_view(), name='review-create'),

    url(r'^orders/$', views.OrderListView.as_view(), name='order-list'),
    url(r'^orders/(?P<pk>[0-9]+)/$', views.OrderDetailView.as_view(), name='order-detail'),
]

cart/urls.py
from django.conf.urls import url

from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.CartView.as_view(), name='cart'),
    url(r'^add/$', views.AddItemToCart.as_view(), name='add'),
    url(r'^remove/$', views.RemoveItemFromCart.as_view(), name='remove'),
    url(r'^info/$', views.information, name='info'),
    url(r'^confirm/$', views.confirmation, name='confirm'),
]

item/urls.py
from django.conf.urls import url

from . import views

app_name = 'item'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^add/$', views.create_item, name='create'),
    url(r'^(?P<slug>[\w-]+)/$', views.ItemDetailDisplay.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', views.edit_item, name='edit'),
    url(r'^(?P<slug>[\w-]+)/delete/$', views.delete_item, name='delete')
]

web_django/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin

from item.views import HomePageView, career, pin
from users import views

# import notifications.urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # url(r'^inbox/notifications/', include(notifications.urls, namespace='notifications')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^api/', include('api.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += i18n_patterns(
    url(r'^$', HomePageView.as_view(), name='index'),
    url(r'^career/$', career, name='career'),
    url(r'^pin/$', pin, name='pin'),
    url(r'^users/', include('users.urls')),
    url(r'^item/', include('item.urls')),
    url(r'^cart/', include('cart.urls')),
    url(r'^order/', include('order.urls')),
    url(r'^reviews/', include('reviews.urls')),
    url(r'^shop/', include('shop.urls')),
    url(r'^notification/', views.notification, name='notification'),
    url(r'^profile/', views.UserProfileUpdate.as_view(), name='profile'),

    # 3rd parties apps
    url(r'^accounts/', include('allauth.urls')),
    url(r'^activity/', include('actstream.urls')),
)

cart/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _


class ItemOrderForm(forms.Form):
    """
    Form for items in order (cart page)
    """
    item_id = forms.IntegerField()
    quantity = forms.IntegerField(min_value=0)


class ItemForm(forms.Form):
    """
    Form for item deletion (cart page)
    """
    item_id = forms.IntegerField()


class InformationForm(forms.Form):
    """
    Form for information page
    """
    name = forms.CharField(max_length=30, label=_('Contact name'))
    email = forms.EmailField(label=_('Email'))
    phone = forms.CharField(max_length=16, label=_('Phone number'))
    address = forms.CharField(max_length=250, label=_('Address'))
    city = forms.CharField(max_length=30, label=_('City'))
    district = forms.CharField(max_length=30, label=_('District'))
    ward = forms.CharField(max_length=30, label=_('Ward'), required=False)
    note = forms.CharField(max_length=250, label=_('Note'), required=False)

cart/views.py
from django.forms import formset_factory
from django.http import HttpResponseBadRequest, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import FormView
from django.utils.translation import ugettext_lazy as _
from django.contrib import messages

from web_django.settings import CART_SESSION, INFO_SESSION

from order.models import ItemOrder, Order
from item.models import Item

from .utils import get_session
from .forms import ItemOrderForm, ItemForm, InformationForm


class CartView(FormView):
    """
    Display Cart page and handle cart update
    """

    template_name = 'cart/cart.html'
    form_class = formset_factory(ItemOrderForm, extra=0)
    success_url = reverse_lazy('cart:cart')
    success_message = _(u'Cart updated!')

    def get_context_data(self, **kwargs):
        context = super(CartView, self).get_context_data(**kwargs)
        context['cart'] = get_session(self.request, CART_SESSION)
        return context

    def get_initial(self):
        cart = get_session(self.request, CART_SESSION)
        initial = [{'item_id': k, 'quantity': v} for k, v in cart.items()]

        return initial

    def post(self, request, *args, **kwargs):
        form = self.get_form()

        if form.is_valid():
            if 'checkout' in request.POST:
                # if the button clicked is 'checkout', redirect to info page
                self.success_url = reverse('cart:info')
                self.success_message = None

            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        cart = get_session(self.request, CART_SESSION)
        formset = form

        # update cart
        for f in formset:
            item_id = f.cleaned_data['item_id']
            quantity = f.cleaned_data['quantity']
            cart.update({str(item_id): quantity})

        # self.request.session[CART_SESSION] = cart
        self.request.session.modified = True
        if self.success_message:
            messages.success(self.request, self.success_message)

        return super(CartView, self).form_valid(form)


class AddItemToCart(FormView):
    """
    Add new item to cart
    """
    form_class = ItemOrderForm

    def get(self, request, *args, **kwargs):
        return HttpResponseBadRequest()

    def form_valid(self, form):
        item_id = form.cleaned_data['item_id']
        quantity = 1

        cart = get_session(self.request, CART_SESSION)
        exist = cart.get(str(item_id))

        if exist:
            cart[str(item_id)] += quantity
        else:
            cart[str(item_id)] = quantity

        self.request.session[CART_SESSION] = cart
        self.request.session.modified = True

        item = Item.objects.get(id=item_id)
        success_message = _(u'{} added to cart!'.format(item.name))
        messages.success(self.request, success_message)

        return HttpResponseRedirect(reverse('cart:cart'))


class RemoveItemFromCart(FormView):
    """
    Delete item from cart
    """
    form_class = ItemForm

    def get(self, request, *args, **kwargs):
        return HttpResponseBadRequest()

    def form_valid(self, form):
        cart = get_session(self.request, CART_SESSION)
        item_id = form.cleaned_data['item_id']

        # remove item from cart session
        if str(item_id) in cart.keys():
            del cart[str(item_id)]

        self.request.session.modified = True

        item = Item.objects.get(id=item_id)
        success_message = _(u'{} removed from cart!'.format(item.name))
        messages.success(self.request, success_message)

        return HttpResponseRedirect(reverse('cart:cart'))


def information(request):
    """
    Information form when ordering
    :param request:
    :return:
    """

    cart = get_session(request, CART_SESSION)
    if not cart:
        return HttpResponseRedirect(reverse('cart:cart'))

    if request.user.is_authenticated():
        profile = request.user.profile
        form = InformationForm(initial={'name': profile.name,
                                        'address': profile.address,
                                        'phone': profile.phone,
                                        'email': profile.email, })
    else:
        form = InformationForm

    if request.method == 'POST':
        form = InformationForm(request.POST)

        if form.is_valid():

            # push data into info session
            info = get_session(request, INFO_SESSION)
            for k, v in form.cleaned_data.items():
                info[str(k)] = v

            request.session[INFO_SESSION] = info
            request.session.modified = True
            return HttpResponseRedirect(reverse('cart:confirm'))

    return render(request, 'cart/information.html', {'form': form})


def confirmation(request):
    """
    Confirmation page and create new order if transaction succeed
    :param request:
    :return:
    """
    cart = get_session(request, CART_SESSION)
    info = get_session(request, INFO_SESSION)

    if not info:
        return HttpResponseRedirect(reverse('cart:info'))

    if request.method == 'POST':
        if request.user.is_authenticated():
            profile = request.user.profile
        else:
            profile = None

        # Create order
        order = Order.objects.create(userprofile=profile,
                                     receiver=info['name'],
                                     note=info['note'],
                                     phone=info['phone'],
                                     address=info['address'],
                                     email=info['email'],
                                     city=info['city'],
                                     district=info['district'], )
        # Create item order
        for item_id, quantity in cart.items():
            item = Item.objects.get(id=item_id)
            ItemOrder.objects.create(order=order, item=item, quantity=quantity)

        # Clear the session
        cart.clear()
        info.clear()
        request.session.modified = True

        return HttpResponseRedirect(reverse('order:detail', args=(str(order.id),)))

    return render(request, 'cart/confirm.html', {'cart': cart, 'info': info})

templates/cart/cart.html
{% extends 'layout/base.html' %}
{% load static %}
{% load humanize %}
{% load cart_tags %}
{% load widget_tweaks %}
{% load i18n %}

{% block title %}
    {% trans 'Cart' %}
{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'order/cart.css' %}">
{% endblock %}

{% block content %}

    <div class="container wrapper">
        <div class="row">
            {% include 'layout/messages_snippet.html' with messages=messages %}
        </div>
        {% if not cart %}
            <div class="alert alert-info">
                {% trans 'Your shopping cart is empty' %}
            </div>
        {% else %}
            <div class="row">
                <div class="col-md-8">
{#                    <div class="card card-1">#}
{#                        <h4>{% trans 'Additional product' %}</h4>#}
{#                        <div id="Carousel" class="carousel slide">#}
{##}
{#                            <!-- Carousel items -->#}
{#                            <div class="carousel-inner">#}
{##}
{#                                <div class="item active">#}
{#                                    <div class="row">#}
{#                                        <div class="col-md-4">#}
{#                                            <a href="#" class="thumbnail">#}
{#                                                <img class="img-responsive" src="{% static "images/coca.jpg" %}"#}
{#                                                     alt="Image">#}
{#                                            </a>#}
{#                                        </div>#}
{#                                        <div class="col-md-4">#}
{#                                            <a href="#" class="thumbnail">#}
{#                                                <img class="img-responsive" src="{% static "images/pepsi.jpg" %}"#}
{#                                                     alt="Image">#}
{#                                            </a>#}
{#                                        </div>#}
{#                                        <div class="col-md-4">#}
{#                                            <a href="#" class="thumbnail">#}
{#                                                <img class="img-responsive" src="{% static "images/sprite.jpg" %}"#}
{#                                                     alt="Image">#}
{#                                            </a>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </div>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}

                    <div class="card card-1">
                        <div class="row">
                            <div class="col-md-10 col-xs-10">
                                <form id="cart_form" action="" method="POST">
                                    {% csrf_token %}

                                    <table class="table">
                                        <thead align="center">
                                        <tr>
                                            <td class="col-md-1 ">&nbsp;</td>
                                            <td class="col-md-3"><h4>{% trans 'Product' %}</h4></td>
                                            <td class="col-md-2"><h4>{% trans 'Price' %}</h4></td>
                                            <td class="col-md-2"><h4>{% trans 'Quantity' %}</h4></td>
                                            <td class="col-md-2"><h4>{% trans 'Subtotal' %}</h4></td>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {{ form.management_form }}
                                        {% for field in form %}
                                            <tr class="row_height">
                                                {% get_item field.item_id.value as item %}
                                                {% get_subtotal field.item_id.value as sub_total %}
                                                <input type="hidden"
                                                       name="form-{{ forloop.counter0 }}-{{ field.item_id.name }}"
                                                       value="{{ field.item_id.value }}"/>


                                                <td class="col-md-2 vert-align">
                                                    <a href="{% url 'item:detail' item.slug %}">
                                                        <img src="{{ item.get_primary_image }}"
                                                             class="img-responsive center-block item_icon"
                                                             alt="item_image">
                                                    </a>
                                                </td>

                                                <td class="col-md-3 vert-align">
                                                    <a href="{% url 'item:detail' item.slug %}">
                                                        <h4>{{ item.name|truncatechars:'20' }}</h4></a>
                                                </td>

                                                <td class="col-md-2 vert-align">
                                                    <span>${{ item.price|intcomma }}</span>
                                                </td>

                                                <td class="col-md-2 vert-align">
                                                    <div>
                                                        <input name="form-{{ forloop.counter0 }}-{{ field.quantity.name }}"
                                                               step="1" min="1" value="{{ field.quantity.value }}"
                                                               title="Qty"
                                                               class="form-control input-sm" size="4" type="number">
                                                    </div>
                                                </td>

                                                <td class="col-md-2 vert-align">
                                                    <span class="amount"><strong>${{ sub_total|intcomma }}</strong></span>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        <tr>
                                            <td colspan="6"></td>
                                        </tr>
                                        </tbody>
                                    </table>
                                    <input class="btn btn-lg btn_color" name="update" value="{% trans 'Update Cart' %}"
                                           type="submit">
                                </form>
                            </div>
                            <div class="col-md-2 col-xs-2">
                                <table class="table">
                                    <thead align="center">
                                    <tr class="del_thead">
                                        <td><h4>&nbsp;</h4></td>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for field in form %}
                                        <tr class="delete_row_height">
                                            <td class="vert-align">
                                                <form id="f-{{ field.item_id.value }}" method="POST"
                                                      action="{% url 'cart:remove' %}">
                                                    {% csrf_token %}
                                                    <input id="item_id-{{ field.item_id.value }}" name="item_id"
                                                           type="hidden"
                                                           value="{{ field.item_id.value }}">
                                                    <button
                                                            onclick="document.forms['f-{{ field.item_id.value }}'].submit(); return false;">
                                                        <span class="glyphicon glyphicon-trash"> </span>
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-4 col-xs-12">
                    <div class="card card-1">
                        {% include "cart/price_panel.html" %}
                        <div class="row text-center margin_top_10">
                            <div class="col-md-12 col-xs-12">
                                <input class="btn btn-lg btn_color btn-block" name="checkout" value="{% trans 'Proceed to checkout' %}"
                                       type="submit" form="cart_form">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}

    </div>
{% endblock %}

{% block footer %}
    {#    <script>#}
    {#        var result = $("#myDiv").height();#}
    {#        alert(result);#}
    {#    </script>#}
{% endblock %}

templates/cart/information.html
{% extends 'layout/base.html' %}
{% load static %}
{% load humanize %}
{% load cart_tags %}
{% load widget_tweaks %}
{% load i18n %}

{% block title %}
    {% trans 'Shipping information' %}
{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'order/cart.css' %}">
    <style>
        input[type='number'] {
            -moz-appearance: textfield;
        }

        input::-webkit-outer-spin-button,
        input::-webkit-inner-spin-button {
            -webkit-appearance: none;
        }

    </style>
{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="card card-1">
                    <h3>{% trans 'Shipping information' %}</h3>
                    <hr>

                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger">
                                    <strong>{{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endif %}

                    <form id="info_form" action="" method="POST">
                        {% csrf_token %}

                        <div class="row">
                            <div class="form-group col-md-6">
                                <label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
                                {% render_field form.name class+="form-control" %}
                            </div>
                            <div class="form-group col-md-6">
                                <label for="{{ form.phone.id_for_label }}">{{ form.phone.label }}</label>
                                {% render_field form.phone class+="form-control" %}
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group col-md-6">
                                <label for="{{ form.address.id_for_label }}">{{ form.address.label }}</label>
                                {% render_field form.address class+="form-control" %}
                            </div>
                            <div class="form-group col-md-6">
                                <label for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
                                {% render_field form.email class+="form-control" %}
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group col-md-4">
                                <label for="id_city">{% trans 'City' %}</label>
                                <select id="id_city" name="city" class="form-control" required>
                                    <option value=""></option>
                                    <option value="Saigon" selected>{% trans 'Saigon' %}</option>
                                    <option value="Hanoi">{% trans 'Hanoi' %}</option>
                                    <option value="Da Nang">{% trans 'Da Nang' %}</option>
                                    <option value="Hai Phong">{% trans 'Hai Phong' %}</option>
                                    <option value="Nha Trang">{% trans 'Nha Trang' %}</option>
                                </select>
                            </div>
                            <div class="form-group col-md-4">
                                <label for="id_district">{% trans 'District' %}</label>
                                <select id="id_district" name="district" class="form-control" required>
                                    <option value=""></option>
                                    <option>1</option>
                                    <option>2</option>
                                    <option>3</option>
                                    <option>7</option>
                                    <option>5</option>
                                </select>
                            </div>
                            <div class="form-group col-md-4">
                                <label for="id_ward">{% trans 'Ward' %}</label>
                                <input id="id_ward" name="ward" class="form-control">
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group col-md-12">
                                <label for="id_note">{% trans 'Note' %}</label>
                                <textarea class="form-control" id="id_note" name="note" rows="5"></textarea>
                                <p class="help-block">{% trans 'eg: no chili, no pepper, etc.' %}</p>
                            </div>
                        </div>

                    </form>
                </div>
            </div>

            <div class="col-md-4 ">
                <div class="card card-1">
                    {% include "cart/price_panel.html" %}
                    <div class="row text-center margin_top_10">
                        <div class="col-md-6">
                            <form action="{% url 'cart:cart' %}">
                                <input type="submit" value="{% trans 'Go back' %}"
                                       class="btn btn-lg btn-block btn_color">
                            </form>
                        </div>
                        <div class="col-md-6">
                            <input type="submit" form="info_form" value="{% trans 'Save and next' %}"
                                   class="btn btn-lg btn-block btn_color">
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>

{% endblock %}

templates/cart/price_panel.html
{% load humanize %}
{% load cart_tags %}
{% load i18n %}

<div class="row">
    <div class="col-md-6 col-xs-6">
        <h4>{% trans 'Subtotal' %}</h4>
    </div>
    <div class="col-md-6 col-xs-6">
        <div class="text-right">
            {% get_total_price as total %}
            <h4 id="total"><strong>${{ total|intcomma }}</strong></h4>
        </div>
    </div>
</div>
<hr>
<div class="row">
    <div class="col-md-6 col-xs-6">
        <h4>{% trans 'Shipping fee' %}</h4>
    </div>
    <div class="col-md-6 col-xs-6">
        <div class="text-right">
            {% get_shipping as shipping %}
            <h4><strong>${{ shipping|intcomma }}</strong></h4>
        </div>
    </div>
</div>
<hr>
<div class="row">
    <div class="col-md-6 col-xs-6">
        <input type="text" class="form-control" placeholder="{% trans 'Coupon code' %}">
    </div>
    <div class="col-md-6 col-xs-6">
        <div class="text-right">
            <button type="button" class="btn btn_color">
                {% trans 'Apply' %}
            </button>
        </div>
    </div>
</div>
<hr>
<div class="row">
    <div class="col-md-6 col-xs-6">
        <h4>{% trans 'Total' %}</h4>
    </div>
    <div class="col-md-6 col-xs-6">
        <div class="text-right">
            {% get_total_with_ship as total_w_ship %}
            <h4><strong>${{ total_w_ship|intcomma }}</strong></h4>
        </div>
    </div>
</div>