api/urls.py
from django.conf.urls import url

from . import views

app_name = 'api'

# Create a router and register our viewsets with it.
# router = DefaultRouter()
# router.register(r'items', views.ItemViewSet)
# router.register(r'users', views.UserViewSet)
# router.register(r'shops', views.ShopViewSet)

urlpatterns = [
    url(r'^$', views.api_root, name='root'),
    # url(r'^', include(router.urls)),

    url(r'^items/$', views.ItemList.as_view(), name='item-list'),
    url(r'^items/(?P<pk>[0-9]+)/$', views.ItemDetail.as_view(), name='item-detail'),

    url(r'^users/$', views.UserList.as_view(), name='user-list'),
    url(r'^users/(?P<pk>[0-9]+)/$', views.UserDetail.as_view(), name='user-detail'),

    url(r'^profile/$', views.UserProfileDetail.as_view(), name='profile'),

    url(r'^shops/$', views.ShopList.as_view(), name='shop-list'),
    url(r'^shops/(?P<pk>[0-9]+)/$', views.ShopDetail.as_view(), name='shop-detail'),

    # url(r'^reviews/(?P<pk>[0-9]+)/$', views.ReviewDetail.as_view(), name='review-detail'),
    url(r'^reviews/$', views.ReviewCreateView.as_view(), name='review-create'),

    url(r'^orders/$', views.OrderListView.as_view(), name='order-list'),
    url(r'^orders/(?P<pk>[0-9]+)/$', views.OrderDetailView.as_view(), name='order-detail'),
]

item/urls.py
from django.conf.urls import url

from . import views

app_name = 'item'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^add/$', views.create_item, name='create'),
    url(r'^(?P<slug>[\w-]+)/$', views.ItemDetailDisplay.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', views.edit_item, name='edit'),
    url(r'^(?P<slug>[\w-]+)/delete/$', views.delete_item, name='delete')
]

reviews/urls.py
from django.conf.urls import url

from . import views

app_name = 'reviews'

urlpatterns = [
    url(r'^$', views.ReviewPageView.as_view(), name='index'),
    url(r'^create/$', views.ItemReview.as_view(), name='create'),
]

web_django/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin

from item.views import HomePageView, career, pin
from users import views

# import notifications.urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # url(r'^inbox/notifications/', include(notifications.urls, namespace='notifications')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^api/', include('api.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += i18n_patterns(
    url(r'^$', HomePageView.as_view(), name='index'),
    url(r'^career/$', career, name='career'),
    url(r'^pin/$', pin, name='pin'),
    url(r'^users/', include('users.urls')),
    url(r'^item/', include('item.urls')),
    url(r'^cart/', include('cart.urls')),
    url(r'^order/', include('order.urls')),
    url(r'^reviews/', include('reviews.urls')),
    url(r'^shop/', include('shop.urls')),
    url(r'^notification/', views.notification, name='notification'),
    url(r'^profile/', views.UserProfileUpdate.as_view(), name='profile'),

    # 3rd parties apps
    url(r'^accounts/', include('allauth.urls')),
    url(r'^activity/', include('actstream.urls')),
)

reviews/models.py
from django.db import models
from django.dispatch import receiver

from item.models import Item
from users.models import UserProfile


# Create your models here.

class Review(models.Model):
    MAX_STARS = 5
    RATING_STARS = (
        (1, 'One star'),
        (2, 'Two stars'),
        (3, 'Three stars'),
        (4, 'Four stars'),
        (5, 'Five stars'),
    )
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name='reviews')
    reviewer = models.ForeignKey(UserProfile)
    content = models.TextField(blank=True, default='')
    rating = models.IntegerField(choices=RATING_STARS, default=4)
    updated_time = models.DateTimeField(auto_now=True)
    approved_comment = models.BooleanField(default=False)

    class Meta:
        unique_together = (("item", "reviewer"),)

    def __str__(self):
        return self.content

    def __unicode__(self):
        return "{}".format(self.content)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_rating(self):
        return range(self.rating)


@receiver(models.signals.post_save, sender=Review)
def update_item_rating(sender, instance, **kwargs):
    """
    Update the rating of item reviewed
    """
    item = instance.item
    item.rating = item.get_rating()
    item.save()

reviews/forms.py
from django.forms import ModelForm
from django import forms

from order.models import ItemOrder
from .models import Review


class ReviewForm(ModelForm):
    item_order_id = forms.IntegerField()

    class Meta:
        model = Review
        fields = ('item', 'rating', 'content', 'item_order_id')

    def save(self, commit=True):
        item_order_id = self.cleaned_data['item_order_id']
        item_order = ItemOrder.objects.get(pk=item_order_id)
        item_order.is_reviewed = True
        item_order.save()

        return super(ReviewForm, self).save(commit=commit)

reviews/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, HttpResponseBadRequest
from django.urls import reverse
from django.views.generic import FormView
from django.views.generic import ListView

from order.models import ItemOrder
from reviews.models import Review
from .forms import ReviewForm


class ReviewPageView(ListView, LoginRequiredMixin):
    '''
    Display all item order that is not reviewed
    '''
    model = ItemOrder
    template_name = 'reviews/review.html'
    context_object_name = 'item_order'

    def get_queryset(self):
        item_order = ItemOrder.objects.filter(order__userprofile=self.request.user.profile,
                                              is_reviewed=False,
                                              order__status='FI')

        return item_order


class ItemReview(FormView, LoginRequiredMixin):
    '''
    Handle review form
    '''
    form_class = ReviewForm

    def get(self, request, *args, **kwargs):
        return HttpResponseBadRequest()

    def form_valid(self, form):
        review = form.save(commit=False)

        item = form.cleaned_data['item']
        reviewer = self.request.user.profile

        if Review.objects.filter(item=item, reviewer=reviewer).exists():
            # Override the old review
            review = Review.objects.get(item=item, reviewer=reviewer)
            review.content = form.cleaned_data['content']
            review.rating = form.cleaned_data['rating']
            review.save()
        else:
            review.reviewer = reviewer
            review.save()

        # After the review is saved, mark the itemorder as reviewed
        # this is done in the save() of form (in forms.py)

        return HttpResponseRedirect(reverse('item:detail', kwargs={'slug': item.slug}))

templates/reviews/review.html
{% extends 'layout/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load i18n %}

{% block title %}
    {% trans 'Reviews' %}
{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'reviews/review.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'profile_panel.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'reviews/rating.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            {% include 'layout/profile_panel_snippet.html' with user=user %}

            <div class="col-md-9">
                {% if not object_list %}
                    <div class="alert alert-info">
                        {% trans 'There is no products to be reviewed.' %}
                    </div>
                {% else %}
                    <div class="row">
                    {% for i in item_order %}
                        <div class="col-md-6">
                            <div class="card">
                                <div class="row">
                                    <div class="col-md-4">
                                        <a href="{% url 'item:detail' i.item.slug %}">
                                            <img class="img-responsive center-block food_img"
                                                 src="{{ i.item.get_primary_image }}"/>
                                        </a>
                                    </div>
                                    <div class="col-md-8">
                                        <p class="food_name">
                                            {{ i.item.name }}
                                        </p>
                                        <p>
                                            <small>{% trans 'from order: ' %} <strong>{{ i.order.order_id }}</strong>
                                            </small>
                                        </p>
                                    </div>

                                </div>

                                <div class="row margin_top_10">
                                    <div class="col-md-12">
                                        <hr id="myHr">
                                        <form id="form-{{ i.item_id }}" method="post"
                                              action="{% url 'reviews:create' %}">
                                            {% csrf_token %}
                                            <input type="hidden" name="item" value="{{ i.item_id }}">
                                            <input type="hidden" name="item_order_id" value="{{ i.id }}">
                                            <p>{% trans 'How much do you rate this product?' %}</p>
                                            <div class="rating">
                                                <input type="radio" id="star5" name="rating" value="5"/>
                                                <label class="full" for="star5"
                                                       title="{% trans 'Awesome' %}!"></label>
                                                <input type="radio" id="star4" name="rating" value="4" checked/>
                                                <label class="full" for="star4"
                                                       title="{% trans 'Pretty good' %}"></label>
                                                <input type="radio" id="star3" name="rating" value="3"/>
                                                <label class="full" for="star3"
                                                       title="{% trans 'Meh' %}"></label>
                                                <input type="radio" id="star2" name="rating" value="2"/>
                                                <label class="full" for="star2"
                                                       title="{% trans 'Not good' %}"></label>
                                                <input type="radio" id="star1" name="rating" value="1"/>
                                                <label class="full" for="star1"
                                                       title="{% trans 'Really bad' %}"></label>
                                            </div>
                                            <div class="full-width pull-left">
                                                <p>{% trans 'What are your comments?' %}</p>
                                            </div>
                                            <div class="full-width">
                                                <textarea id="id_content" name="content" cols="45" rows="8"
                                                          aria-required="true" class="form-control"></textarea>
                                            </div>

                                        </form>
                                    </div>
                                </div>

                                <div class="row margin_top_10">
                                    <div class="col-md-12">
                                        <button type="submit" form="form-{{ i.item_id }}"
                                                class="btn btn_color pull-right">{% trans 'Done' %}
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
                </div>
            </div>
        </div>

    </div>
{% endblock %}