api/urls.py
from django.conf.urls import url

from . import views

app_name = 'api'

# Create a router and register our viewsets with it.
# router = DefaultRouter()
# router.register(r'items', views.ItemViewSet)
# router.register(r'users', views.UserViewSet)
# router.register(r'shops', views.ShopViewSet)

urlpatterns = [
    url(r'^$', views.api_root, name='root'),
    # url(r'^', include(router.urls)),

    url(r'^items/$', views.ItemList.as_view(), name='item-list'),
    url(r'^items/(?P<pk>[0-9]+)/$', views.ItemDetail.as_view(), name='item-detail'),

    url(r'^users/$', views.UserList.as_view(), name='user-list'),
    url(r'^users/(?P<pk>[0-9]+)/$', views.UserDetail.as_view(), name='user-detail'),

    url(r'^profile/$', views.UserProfileDetail.as_view(), name='profile'),

    url(r'^shops/$', views.ShopList.as_view(), name='shop-list'),
    url(r'^shops/(?P<pk>[0-9]+)/$', views.ShopDetail.as_view(), name='shop-detail'),

    # url(r'^reviews/(?P<pk>[0-9]+)/$', views.ReviewDetail.as_view(), name='review-detail'),
    url(r'^reviews/$', views.ReviewCreateView.as_view(), name='review-create'),

    url(r'^orders/$', views.OrderListView.as_view(), name='order-list'),
    url(r'^orders/(?P<pk>[0-9]+)/$', views.OrderDetailView.as_view(), name='order-detail'),
]

chef/urls.py
from django.conf.urls import url

from . import views

app_name = 'chef'

urlpatterns = [
    # url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^dashboard/$', views.DashboardView.as_view(), name='dashboard'),
    url(r'^(?P<slug>[\w-]+)/$', views.ChefView.as_view(), name='detail'),
]

item/urls.py
from django.conf.urls import url

from . import views

app_name = 'item'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^add/$', views.create_item, name='create'),
    url(r'^(?P<slug>[\w-]+)/$', views.ItemDetailDisplay.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', views.edit_item, name='edit'),
    url(r'^(?P<slug>[\w-]+)/delete/$', views.delete_item, name='delete')
]

users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'

urlpatterns = [
    # url(r'^$', views.IndexView.as_view(), name='index'),
    # url(r'^(?P<slug>[\w-]+)/$', views.ChefView.as_view(), name='detail'),
]

web_django/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin

from item.views import HomePageView, career, pin
from users import views

# import notifications.urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # url(r'^inbox/notifications/', include(notifications.urls, namespace='notifications')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^api/', include('api.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += i18n_patterns(
    url(r'^$', HomePageView.as_view(), name='index'),
    url(r'^career/$', career, name='career'),
    url(r'^pin/$', pin, name='pin'),
    url(r'^users/', include('users.urls')),
    url(r'^item/', include('item.urls')),
    url(r'^cart/', include('cart.urls')),
    url(r'^order/', include('order.urls')),
    url(r'^reviews/', include('reviews.urls')),
    url(r'^shop/', include('shop.urls')),
    url(r'^notification/', views.notification, name='notification'),
    url(r'^profile/', views.UserProfileUpdate.as_view(), name='profile'),

    # 3rd parties apps
    url(r'^accounts/', include('allauth.urls')),
    url(r'^activity/', include('actstream.urls')),
)

users/models.py
import os

import itertools
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User

from allauth.account.models import EmailAddress
from allauth.socialaccount.models import SocialAccount
from django.utils.text import slugify

from .validators import numeric


class UserProfile(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='profile')
    name = models.CharField(max_length=30, default='users')

    # Customer information
    slug = models.SlugField(unique=True, max_length=100)  # for URL
    avatar = models.ImageField(upload_to='uploads/%Y/%m/%d', blank=True, null=True,
                               default=os.path.join(settings.STATIC_URL, "images/default-avatar.png"))
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, null=True)
    birthday = models.DateField(null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    phone = models.CharField(max_length=15, validators=(numeric,), null=True, blank=True)
    allergy = models.TextField(null=True, blank=True, max_length=100)
    point = models.PositiveIntegerField(default=0)

    #  Address information
    address = models.TextField(null=True, blank=True, max_length=100)
    city = models.CharField(max_length=30, null=True, blank=True)
    district = models.CharField(max_length=30, null=True, blank=True)
    ward = models.CharField(max_length=30, null=True, blank=True)

    #  For shop
    is_shop = models.BooleanField(default=False)
    info = models.TextField(null=True, blank=True)

    # Extra
    avatar_link = models.URLField(default='', null=True, blank=True)

    def __unicode__(self):
        return "{}'s profile".format(self.user.username)

    def __str__(self):  # Python 2
        return "%s's profile" % self.user.username

    class Meta:
        db_table = 'user_profile'

    def save(self, *args, **kwargs):
        if not self.id:
            # Newly created object, so set slug
            self.slug = orig = slugify(self.get_username())
            print(self.name)

            for x in itertools.count(1):
                if not UserProfile.objects.filter(slug=self.slug).exists():
                    break
                self.slug = "{}-{}".format(orig, x)
        super(UserProfile, self).save(*args, **kwargs)

    def account_verified(self):
        if self.user.is_authenticated:
            result = EmailAddress.objects.filter(email=self.user.email)
            if len(result):
                return result[0].verified
        return False

    def get_username(self):
        if self.user.last_name and self.user.first_name:
            return self.user.last_name + " " + self.user.first_name
        elif self.user.username:
            return self.user.username

    def get_email(self):
        if self.user.email:
            return self.user.email

    def get_phone(self):
        if self.user.phone:
            return self.user.phone

    def get_birthday(self):
        return {'day': self.birthday.day,
                'month': self.birthday.month,
                'year': self.birthday.year}


User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

from .validators import alphabet, numeric
from .models import UserProfile

BIRTH_YEAR_CHOICES = [x for x in range(1960, 2016, 1)]


class SignupForm(forms.Form):
    last_name = forms.CharField(max_length=30, label=_('Last name'), validators=(alphabet,),
                                widget=forms.TextInput(attrs={'placeholder': _('Last name')}))
    first_name = forms.CharField(max_length=30, label=_('First name'), validators=(alphabet,),
                                 widget=forms.TextInput(attrs={'placeholder': _('First name')}))
    phone = forms.CharField(label=_("Phone"), validators=(numeric,),
                            widget=forms.TextInput(attrs={'placeholder': _('Phone number')}))
    email = forms.EmailField(label=_("Email"))
    password1 = forms.CharField(max_length=16, widget=forms.PasswordInput)
    password2 = forms.CharField(max_length=16, widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['last_name', 'first_name', 'phone', 'email', 'password1', 'password2']

    def signup(self, request, user):
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.phone = self.cleaned_data['phone']
        user.email = self.cleaned_data['email']
        user.password = self.cleaned_data['password2']
        if user.password:
            user.set_password(user.password)
        else:
            user.set_unusable_password()
        user.save()

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if not password2:
            raise forms.ValidationError("You must confirm your password")
        if password1 != password2:
            raise forms.ValidationError("Your passwords do not match")
        return password2


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['birthday', 'gender', 'email', 'phone', 'address', 'allergy', 'city', 'district', 'ward']
        widgets = {
            'birthday': forms.SelectDateWidget(years=BIRTH_YEAR_CHOICES),
            'address': forms.Textarea(attrs={'rows': 1}),
            'allergy': forms.Textarea(attrs={'rows': 1})
        }
        labels = {
            'birthday': _('Birthday'),
            'gender': _('Gender'),
            'phone': _('Phone number'),
            'address': _('Address'),
            'allergy': _('Allergy history'),
            'city': _('City'),
            'district': _('District'),
            'ward': _('Ward')
        }

    email = forms.CharField(disabled=True)

users/views.py
from actstream.models import any_stream
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render
from django.views import generic
from django.utils.translation import ugettext_lazy as _

from users.models import UserProfile
from .forms import UserProfileForm


class UserProfileUpdate(SuccessMessageMixin, LoginRequiredMixin, generic.UpdateView):
    '''
    User profile page: /accounts/profile
    '''
    model = UserProfile
    form_class = UserProfileForm
    template_name = 'users/profile.html'
    success_url = '.'
    success_message = _(u'Changes saved')

    def get_object(self, queryset=None):
        return self.request.user.profile


@login_required
def notification(request):
    actions = any_stream(request.user.profile)
    return render(request, 'users/notification.html', {'actions': actions})

templates/users/detail.html
{% extends 'layout/base.html' %}
{% load static %}

{% block title %}
    {{ user.profile.name }}
{% endblock %}

{% block css %}
{% endblock %}

{% block content %}
    <div class="container wrapper">
        {% if user.profile.avatar %}
            <img class="avatar" src="{{ user.profile.avatar.url }}" alt="avatar"/>
        {% else %}
            <img class="avatar" src="{% static 'images/default-avatar.png' %}" alt="avatar"/>
        {% endif %}

        <p>{{ user.profile.name }}</p>
        <p>{{ user.profile.address }}</p>
        <p>{{ user.profile.phone }}</p>
        <p>{{ user.profile.email }}</p>
        <p>{{ user.profile.info }}</p>
        <p>{{ user.date_joined }}</p>

        {% if items %}
            <ul>
                {% for item in items %}
                    <a href="{% url 'item:detail' item.slug %}">
                        {# <img class="img-responsive" src="{{ item.get_primary_image }}"/>#}
                        {{ item.name }}
                    </a>
                {% endfor %}
            </ul>
        {% else %}
            <p>No items are available.</p>
        {% endif %}

    </div>
{% endblock %}

templates/users/index.html
{% extends 'layout/base.html' %}

{% block content %}
    <div class="container">
        {% if list_users %}
            <ul>
                {% for u in list_users %}
                    <li><a href="{% url 'users:detail' u.profile.slug %}">{{ u.profile.name }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No users are available.</p>
        {% endif %}
    </div>
{% endblock %}

templates/users/notification.html
{% extends 'layout/base.html' %}
{% load static %}
{% load activity_tags %}
{% load i18n %}

{% block title %}
    {% trans 'Notification' %}
{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'noti.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'profile_panel.css' %}">
{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            {% include 'layout/profile_panel_snippet.html' with user=user %}

            <div class="col-md-9">
                <div class="card card-1">
                    <div class="row">
                        <div class="col-md-12">
                            <h4>Thông báo của tôi</h4>

                            <ul class="nav nav-tabs">
                                <li class="active">
                                    <a data-toggle="tab" href="#promotion">{% trans 'Promotions' %}</a>
                                </li>
                                <li>
                                    <a data-toggle="tab" href="#information">{% trans 'Orders status' %}</a>
                                </li>
                            </ul>

                            <div class="tab-content">
                                <div id="promotion" class="tab-pane fade in active promotion">
                                    <a href="sharing.html"><img class="img-responsive marketing_banner"
                                                                src="{% static 'images/banner.jpg' %}"> </a>
                                    <a href="#"> <img class="img-responsive marketing_banner"
                                                      src="{% static 'images/banner2.jpg' %}"></a>
                                    <a href="#"> <img class="img-responsive marketing_banner"
                                                      src="{% static 'images/banner3.jpg' %}"></a>
                                </div>

                                <div id="information" class="tab-pane fade">
                                    {#                                        {% for action in actions %}#}
                                    {#                                            {% display_action action %}#}
                                    {#                                                                            {% empty %}#}
                                    {#                                                                                <p>Nothing here</p>#}
                                    {#                                                                            {% endfor %}#}

                                    {% for event in actions %}
                                        <div class="row promotion_tab">
                                            <div id="date" class="col-md-2 col-xs-12 date">
                                                <p>{{ event.timestamp|date:"SHORT_DATE_FORMAT" }}</p>
                                            </div>
                                            <div class="col-md-8 col-xs-12">
                                                <p>
                                                    {% if event.verb == 'is changed' %}
                                                        {# {% trans 'Order' %}#}
                                                        {% if event.action_object %}
                                                            <strong>#{{ event.action_object.order_id }}</strong>
                                                        {% endif %}
                                                        {{ event.verb }}
                                                        {% if event.data.status %}
                                                            <strong>{{ event.data.status }}</strong>
                                                        {% endif %}

                                                    {% elif event.verb == 'is canceled' %}
                                                        {% trans 'Order' %}
                                                        {% if event.action_object %}
                                                            <strong>#{{ event.action_object.order_id }}</strong>
                                                        {% endif %}
                                                        {{ event.verb }}

                                                    {% else %}

{#                                                        {% if request.user.profile == event.actor %}#}
{#                                                            {% trans 'You' %}#}
{#                                                        {% else %}#}
{#                                                            {{ event.actor.name }}#}
{#                                                        {% endif %}#}
                                                        {% if event.action_object %}
                                                            <strong>#{{ event.action_object.order_id }}</strong>
                                                        {% endif %}
                                                        {{ event.verb }}

                                                    {% endif %}
                                                </p>
                                            </div>
                                        </div>
                                    {% empty %}
                                        <div class="alert alert-info margin_top_10">
                                            {% trans 'You have not ordered yet' %}
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div> <!-- close col div -->
        </div>
    </div>

{% endblock %}


{% block footer %}
    <script>
        var hash = document.location.hash;
        var prefix = "tab_";
        if (hash) {
            $('.nav-tabs a[href="' + hash.replace(prefix, "") + '"]').tab('show');
        }

        // Change hash for page-reload
        $('.nav-tabs a').on('shown.bs.tab', function (e) {
            console.log("abc")
            window.location.hash = e.target.hash.replace("#", "#" + prefix);
        });
    </script>
{% endblock %}

templates/users/profile.html
{% extends "layout/base.html" %}
{% load static %}
{% load widget_tweaks %}
{% load i18n %}

{% block title %}
    {{ user.profile.name }}
{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'users/profile.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'profile_panel.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            {% include 'layout/profile_panel_snippet.html' with user=user %}

            <div class="col-md-9">
                <div class="card card-1">

                    <form method="POST">
                        {% csrf_token %}
                        <div class="row">

                            {% include 'layout/messages_snippet.html' with messages=messages %}
                            <div class="col-md-12">
                                {% if form.errors %}
                                {% for field in form %}
                                    {% for error in field.errors %}
                                        <div class="alert alert-danger">
                                            {{ error|escape }}
                                        </div>
                                    {% endfor %}
                                {% endfor %}
                                {% for error in form.non_field_errors %}
                                    <div class="alert alert-warning">
                                        {{ error|escape }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                            </div>

                            <div class="col-md-7">
                                <div class="form-group">
                                    <label>{% trans 'Full name' %}</label>
                                    <div class="form-control-static">
                                        {{ userprofile.name }}
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
                                    {% render_field form.email class+="form-control" %}
                                </div>

                                <div class="form-group">
                                    <label for="{{ form.address.id_for_label }}">{{ form.address.label }}</label>
                                    {% render_field form.address class+="form-control" %}
                                </div>

                                <div class="row">
                                    <div class="form-group col-md-4">
                                        <label for="id_city">Tỉnh/Thành Phố</label>
                                        <select id="id_city" name="city" class="form-control">
                                            <option value="SG">Sài Gòn</option>
                                        </select>
                                    </div>

                                    <div class="form-group col-md-4">
                                        <label for="id_district">Quận/Huyện</label>
                                        <select id="id_district" name="district" class="form-control">
                                            <option value="Q1">Q1</option>
                                            <option value="Q2">Q2</option>
                                            <option value="Q3">Q3</option>
                                            <option value="Q4">Q4</option>
                                            <option value="Q5">Q5</option>
                                            <option value="Q7">Q7</option>
                                            <option value="Q8">Q8</option>
                                        </select>
                                    </div>

                                    <div class="form-group col-md-4">
                                        <label for="{{ form.ward.id_for_label }}">{{ form.ward.label }}</label>
                                        {% render_field form.ward class+="form-control" %}
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-5">
                                <div class="form-group">
                                    <label for="{{ form.birthday.id_for_label }}">{{ form.birthday.label }}</label>
                                    {#                                <input id="id_birthday_month" name="birthday_month" type="date" class="form-control" placeholder="01/01/19xx ">#}
                                    <div class="display_text">
                                        {% if userprofile.birthday %}
                                            {{ userprofile.birthday }}

                                            {% with userprofile.get_birthday as birthday %}
                                                <input type="hidden" name="birthday_day" value="{{ birthday.day }}">
                                                <input type="hidden" name="birthday_month" value="{{ birthday.month }}">
                                                <input type="hidden" name="birthday_year" value="{{ birthday.year }}">
                                            {% endwith %}

                                        {% else %}
                                            {% render_field form.birthday class+="form-control" %}
                                        {% endif %}

                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="{{ form.phone.id_for_label }}">{{ form.phone.label }}</label>
                                    {% render_field form.phone class+="form-control" %}
                                </div>

                                <div class="form-group">
                                    <label for="{{ form.gender.id_for_label }}">{{ form.gender.label }}</label>
                                    {% render_field form.gender class+="form-control" %}
                                </div>

                                <div class="form-group">
                                    <label for="{{ form.allergy.id_for_label }}">{{ form.allergy.label }}</label>
                                    {% render_field form.allergy class+="form-control" %}
                                    {#                                <p class="help-block">Vd: Không ớt, không hạt tiêu,.. hoặc các thành phần mà bạn bị dị#}
                                    {#                                    ứng</p>#}
                                </div>
                            </div>
                        </div>

                        <div class="row text-center margin_top_10">
                            <button type="submit" class="btn btn_color">{% trans 'Update' %}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        {#        <p>Join date: {{ user.date_joined }}</p>#}

    </div>

{% endblock content %}

{% block footer %}
{% endblock %}