api/urls.py
from django.conf.urls import url

from . import views

app_name = 'api'

# Create a router and register our viewsets with it.
# router = DefaultRouter()
# router.register(r'items', views.ItemViewSet)
# router.register(r'users', views.UserViewSet)
# router.register(r'shops', views.ShopViewSet)

urlpatterns = [
    url(r'^$', views.api_root, name='root'),
    # url(r'^', include(router.urls)),

    url(r'^items/$', views.ItemList.as_view(), name='item-list'),
    url(r'^items/(?P<pk>[0-9]+)/$', views.ItemDetail.as_view(), name='item-detail'),

    url(r'^users/$', views.UserList.as_view(), name='user-list'),
    url(r'^users/(?P<pk>[0-9]+)/$', views.UserDetail.as_view(), name='user-detail'),

    url(r'^profile/$', views.UserProfileDetail.as_view(), name='profile'),

    url(r'^shops/$', views.ShopList.as_view(), name='shop-list'),
    url(r'^shops/(?P<pk>[0-9]+)/$', views.ShopDetail.as_view(), name='shop-detail'),

    # url(r'^reviews/(?P<pk>[0-9]+)/$', views.ReviewDetail.as_view(), name='review-detail'),
    url(r'^reviews/$', views.ReviewCreateView.as_view(), name='review-create'),

    url(r'^orders/$', views.OrderListView.as_view(), name='order-list'),
    url(r'^orders/(?P<pk>[0-9]+)/$', views.OrderDetailView.as_view(), name='order-detail'),
]

cart/urls.py
from django.conf.urls import url

from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.CartView.as_view(), name='cart'),
    url(r'^add/$', views.AddItemToCart.as_view(), name='add'),
    url(r'^remove/$', views.RemoveItemFromCart.as_view(), name='remove'),
    url(r'^info/$', views.information, name='info'),
    url(r'^confirm/$', views.confirmation, name='confirm'),
]

item/urls.py
from django.conf.urls import url

from . import views

app_name = 'item'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^add/$', views.create_item, name='create'),
    url(r'^(?P<slug>[\w-]+)/$', views.ItemDetailDisplay.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', views.edit_item, name='edit'),
    url(r'^(?P<slug>[\w-]+)/delete/$', views.delete_item, name='delete')
]

order/urls.py
from django.conf.urls import url

from . import views

app_name = 'order'

urlpatterns = [
    url(r'^$', views.ListOrdersView.as_view(), name='list'),
    url(r'^(?P<pk>[0-9]+)/$', views.OrderDetailView.as_view(), name='detail'),
]

shop/urls.py
from django.conf.urls import url

from . import views

app_name = 'shop'

urlpatterns = [
    # url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^dashboard/$', views.DashboardView.as_view(), name='dashboard'),
    url(r'^(?P<slug>[\w-]+)/$', views.ShopView.as_view(), name='detail'),
]

web_django/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin

from item.views import HomePageView, career, pin
from users import views

# import notifications.urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # url(r'^inbox/notifications/', include(notifications.urls, namespace='notifications')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^api/', include('api.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += i18n_patterns(
    url(r'^$', HomePageView.as_view(), name='index'),
    url(r'^career/$', career, name='career'),
    url(r'^pin/$', pin, name='pin'),
    url(r'^users/', include('users.urls')),
    url(r'^item/', include('item.urls')),
    url(r'^cart/', include('cart.urls')),
    url(r'^order/', include('order.urls')),
    url(r'^reviews/', include('reviews.urls')),
    url(r'^shop/', include('shop.urls')),
    url(r'^notification/', views.notification, name='notification'),
    url(r'^profile/', views.UserProfileUpdate.as_view(), name='profile'),

    # 3rd parties apps
    url(r'^accounts/', include('allauth.urls')),
    url(r'^activity/', include('actstream.urls')),
)

templates/layout/base.html
{% load static %}
{% load i18n %}
{#{% load notifications_tags %}#}
{#{% load my_noti_tags %}#}

<!DOCTYPE html>
<html lang="en">
<!--
__/\\\\\\\\\\\\_____/\\\________/\\\_
 _\/\\\////////\\\__\/\\\_____/\\\//__
  _\/\\\______\//\\\_\/\\\__/\\\//_____
   _\/\\\_______\/\\\_\/\\\\\\//\\\_____
    _\/\\\_______\/\\\_\/\\\//_\//\\\____
     _\/\\\_______\/\\\_\/\\\____\//\\\___
      _\/\\\_______/\\\__\/\\\_____\//\\\__
       _\/\\\\\\\\\\\\/___\/\\\______\//\\\_
        _\////////////_____\///________\///__
    Just a nonsense line
-->
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} DK {% endblock %}</title>

    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.7/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'sticky-footer-navbar.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'navbar.css' %}">
    {#    <link rel="stylesheet" type="text/css" href="{% static 'notifications/notification.css' %}">#}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">

    {% block css %}{% endblock %}
    <link rel="shortcut icon" href="{% static 'images/logo.png' %}" type="image/x-icon"/>
</head>
<body>

<nav class="navbar navbar-custom navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'index' %}">DK</a>
        </div>

        <div class="collapse navbar-collapse" id="navbar">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'cart:cart' %}"><i class="fa fa-shopping-cart fa-lg"></i> <span
                            class="visible-xs-inline">{% trans 'Cart' %}</span> </a>
                </li>
                {% if user.is_authenticated %}
                    <li class="dropdown" id="aa">

                        <a href="#" class="dropdown-toggle profile-image" data-toggle="dropdown">
                            {% if user.profile.avatar %}
                                <img class="img-circle" width="30px" height="30px"
                                     src="{{ user.profile.avatar.url }}"
                                     alt="{{ user.profile.name }}"/>
                            {% else %}
                                <img class="img-circle" width="30px" height="30px"
                                     src="{% static "images/default-avatar.png" %}"
                                     alt="avatar"/>
                            {% endif %}
                        </a>

                        <ul class="dropdown-menu">
                            <li><a href="{% url 'pin' %}" class="hidden-sm"><i class="fa fa-heart"></i> {% trans 'Pin' %} </a></li>
                            <li>
                                {% if user.profile.is_shop %}
                                    <a href="{% url 'shop:dashboard' %}" class="hidden-sm"><i
                                            class="fa fa-tachometer"></i> {% trans 'Dashboard' %} </a>
                                {% else %}
                                    <a href="{% url 'career' %}" class="hidden-sm">
                                        <i class="fa fa-star-o"></i> {% trans 'Work with us!' %} </a>
                                {% endif %}
                            </li>
                            <li>
                                <a href='{% url 'profile' %}' class="hidden-sm">
                                    <i class="fa fa-user"></i> {% trans 'Profile' %} </a>
                            </li>
                            <li>
                                <a href="{% url 'account_logout' %}" class="hidden-sm">
                                    <i class="fa fa-sign-out" aria-hidden="true"></i> {% trans 'Sign out ' %}</a>
                            </li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'account_login' %}" class="hidden-sm"> {% trans 'Sign in' %} </a></li>
                {% endif %}

            </ul>
            <form class="navbar-form navbar-right search-form" role="search">
                <input type="text" class="form-control" placeholder="{% trans 'Search' %}"/>
            </form>

            <form action="{% url "set_language" %}" method="post" class="navbar-form navbar-right">
                {% csrf_token %}
                <div class="form-group">
                    <select name="language" class="form-control custom" onchange="this.form.submit()">
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}

                        {% for language in languages %}
                            <option value="{{ language.code }}"
                                    {% if language.code == LANGUAGE_CODE %}selected="selected"{% endif %}>
                                {{ language.code|upper }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
            </form>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

{% block content %}
{% endblock %}

<footer class="footer">
    <div class="container">
        <hr>
        <p class="text-muted text-center">&copy; 2016 DK. All Rights Reserved.</p>
    </div>
</footer>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="{% static 'bootstrap-3.3.7/js/bootstrap.min.js' %}"></script>
{#        <script>#}
{#            /* Show dropdown when hover */#}
{#            $('ul.nav li.dropdown').hover(function () {#}
{#                $(this).find('.dropdown-menu').stop(true, true).delay(200).fadeIn(100);#}
{#            }, function () {#}
{#                $(this).find('.dropdown-menu').stop(true, true).delay(200).fadeOut(100);#}
{#            });#}
{#        </script>#}

{# Notification #}
{#<script src="{% static 'notifications/notify.js' %}" type="text/javascript"></script>#}
{#<script src="{% static 'notifications/notification.js' %}" type="text/javascript"></script>#}
{#{% register_notify_callbacks callbacks='fill_notification_badge,gen_notification_list' %}#}

{% block footer %}
{% endblock %}

</body>
</html>

templates/layout/coming_soon.html
{% load static %}
<div class="container">
    <div style="margin-top: 10%">
        <img class="img-responsive" src="{% static 'images/coming-soon.png' %}"/>
    </div>
</div>

templates/layout/item_snippet.html
{% load humanize %}
<div class="col-sm-4">
    <div class="col-item border-no">
        <div class="photo">
            <a href="{% url 'item:detail' item.id %}">
                <img src="{{ item.image.url }}" class="img-responsive" alt="a"/>
            </a>
        </div>
        <div class="separator clear-left">
            <h5 class="color">{{ item.name }}</h5>
            <h4 class="price-text-color">{{ item.price|intcomma }}</h4>
        </div>
    </div>
</div>

templates/layout/login_modal.html
{% load i18n %}
<!-- BEGIN # MODAL LOGIN -->
<section id="login">
    <div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true"
         style="display: none;">
        <div id="login-overlay" class="modal-dialog">
            <div class="modal-content">
                {#            <div class="modal-header">#}
                {#                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span#}
                {#                        class="sr-only">Close</span></button>#}
                {#                <h4 class="modal-title" id="myModalLabel">Login to site.com</h4>#}
                {#            </div>#}
                <div class="modal-body">

                    <div class="form-wrap">
                        <h1>Log in with your email account</h1>
                        <form method="POST" action="{% url 'account_login' %}" autocomplete="off">
                            {% csrf_token %}

                            <div class="form-group">
                                <label for="id_login" class="sr-only">Email</label>
                                <input autofocus="autofocus" class="form-control" id="id_login" name="login"
                                       placeholder="somebody@example.com" type="email" required/>
                            </div>

                            <div class="form-group">
                                <label for="id_password" class="sr-only">Password</label>
                                <input class="form-control" id="id_password" name="password" placeholder="Password"
                                       type="password" required/>
                            </div>

                            <div class="checkbox">
                                <span class="character-checkbox" onclick="showPassword()"></span>
                                <span class="label">Remember me</span>
                            </div>

{#                            <div class="form-group checkbox-inline margin_top_10">#}
{#                                <label for="id_remember">#}
{#                                    <input id="id_remember" name="remember" type="checkbox"/>Remember me</label>#}
{#                            </div>#}

                            <button class="btn btn-custom btn-lg btn-block" type="submit">
                                {% trans "Sign in" %}
                            </button>
                        </form>

                        <a href="{% url 'account_reset_password' %}" class="forget">Forgot your password?</a>
                        <hr>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <!-- END # MODAL LOGIN -->
</section>

templates/layout/messages_snippet.html
<div class="col-md-12">
    {% if messages %}
        {% for message in messages %}
            <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
</div>

templates/layout/profile_panel_snippet.html
{% load static %}
{% load i18n %}

<div class="col-md-3">
    <div class="profile-sidebar card">

        <div class="profile-userpic">
            {% if user.profile.avatar %}
                <img class="img-responsive img-circle" src="{{ user.profile.avatar.url }}" alt="avatar"/>
            {% else %}
                <img class="img-responsive img-circle" src="{% static 'images/default-avatar.png' %}" alt="avatar"/>
            {% endif %}
        </div>

        <div class="profile-usertitle">
            <div class="profile-usertitle-name">
                {{ user.profile.name }}
            </div>
        </div>

        <div class="profile-usermenu">
            <ul class="nav">
                {% url 'profile' as profile_url %}
                {% url 'order:list' as order_url %}
                {% url 'reviews:index' as review_url %}
                {% url 'notification' as noti_url %}
                {% url 'account_change_password' as pwd_url %}
                {% url 'account_set_password' as pwd_set_url %}


                <li {% if request.get_full_path == profile_url %}class="active"{% endif %}>
                    <a href="{{ profile_url }}"> <i class="fa fa-home"></i> {% trans 'Overview' %}</a>
                </li>
                <li {% if request.get_full_path == order_url %}class="active"{% endif %}>
                    <a href="{{ order_url }}"> <i class="fa fa-history"></i> {% trans 'Order history' %}</a>
                </li>
                <li {% if request.get_full_path == review_url %}class="active"{% endif %}>
                    <a href="{{ review_url }}"><i class="fa fa-check"></i> {% trans 'Reviews' %}</a>
                </li>

                <li {% if request.get_full_path == noti_url %}class="active"{% endif %}>
                    <a href="{{ noti_url }}"><i class="fa fa-comment-o"></i> {% trans 'Notifications' %}</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-money"></i> {% trans 'Food Coin' %}</a>
                </li>
                <li {% if request.get_full_path == pwd_url or request.get_full_path == pwd_set_url %}class="active"{% endif %}>
                    <a href="{% url 'account_change_password' %}">
                        <i class="fa fa-cog"></i>
                        {% if user.has_usable_password %}
                            {% trans 'Change password' %}
                        {% else %}
                            {% trans 'Set password' %}
                        {% endif %}
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

templates/layout/review_snippet.html
{% with review.reviewer as u %}
    <div class="col-md-3 col-lg-3">
        <div class="card">
            <div class="row">
                <div class="col-md-7 col-xs-7 rate">
                    {% for foo in review.get_rating %}
                        <label> </label>
                    {% endfor %}
                </div>
                <div class="col-md-5 col-xs-5">
                    <p class="date">{{ review.updated_time|date:"SHORT_DATE_FORMAT" }}</p>
                </div>
                <div class="col-md-12">
                    <p class="review-content">{{ review.content }}</p>
                </div>

                <div class="col-md-2 col-xs-2">
                    <img class="img-circle user_img" src="{{ u.avatar.url }}">
                </div>
                <div class="col-md-10 col-xs-10">
                    <p class="user_name">{{ u.name }}</p>
                </div>
            </div>
        </div>
    </div>
{% endwith %}